title: Naomi Smuczers Portfolio
name: Naomi Smuczer
email: W0631259@myscc.ca
baseurl: "/.github.io"
instagram:
linkedIn:


collections: 
  design:
    output: true
    permalink: /:collection/:path/



